### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by chmiiller** [McDo/tipop#6]
I'm getting this error when try to build the app for iOS Device:
![screen shot 2015-07-28 at 13 05 18](https://cloud.githubusercontent.com/assets/1013632/8929925/70d01168-3529-11e5-86bd-fa09f8564351.png)
Do you know what is that?
The module is awesome and works pretty well on simulator!

**Comment by McDo** [comment]
It means you should create the Ti.UI.ScrollView and Ti.UI.3DMatrix in
advance in order to use this module. Before 4.1.0.GA, I created a
metadata.json file and put these snippet

{"exports": [
"Ti.UI.create3DMatrix",
"Ti.UI.createScrollView",
"Ti.UI.createLabel"
]}

to solve, maybe 4.1.0.GA doesn't take this file into account anymore.
Here you can add the same file into your project, or create those 3
things before import the module. Or, just use tipop-1.0.4 instead.
I'll fix this problem as soon as possible.

**Comment by chmiiller** [comment]
All right, built it successfully with 1.0.4!
Thank you for the quickly response...this module is exactly what I need!
Thank you again

**Comment by McDo** [comment]
@chmiiller 1.0.5 is ready to use now.

**Comment by chmiiller** [comment]
Awesome! I've tested it and it's working well =)
Thank you
